### PR TITLE
Update model to predict second-level.

### PR DESCRIPTION
**Pull request by ptigas**
top-level can be inferred by induction (e.g. for predicted `business-marketing`, top-level is `business` and second-level is `marketing`).

Accuracy of second-level classifier:  `69.91%`
Accuracy of top-level classifier (by induction):  `76.82%`

### CODE REVIEW

**Comment by mrose17** [comment]
@ptigas - is this the list you are using for categories https://support.aerserv.com/hc/en-us/articles/207148516-List-of-IAB-Categories

? if so, it would be much better if the class names were the IAB codes, e.g., "IAB1-1" instead of "Books & Literature" since it makes the induction algorithm much simpler...

your thoughts?

**Comment by ptigas** [comment]
The categories contain both top level and second level, delimited by '-' (e.g. "arts & entertainment-animation" for top-level: "arts & entertainment", second-level: "animation"). It's easy to infer top-level by just extracting `predicted_category.split('-')[0]`.

If you still prefer IAB codes, it's fine with me, it's just we will need the extra file for mapping IAB code to category name.

**Comment by ptigas** [comment]
@mrose17 it looks like the taxonomy cannot be mapped to the IAB taxonomy above (there are entries like anime that don't exist in IAB). we can invent a similar coding / mapping if that helps..

**Comment by mrose17** [comment]
@ptigas - thanks! i've reviewed the file and agree with the approach you've taken. thanks!

**Pull request merged**
